config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  resources :dates, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :records, only: [:create, :destroy]
  end

  resources :feedpod_dates, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :feedpod_records, only: [:create, :destroy]
  end

  resources :insights, only: [:index]

  get 'statics/visual'
  get 'statics/exhibit'

  root 'insights#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dates_controller.rb
class DatesController < ApplicationController

  def index
    @dates = Day.all.order("created_at DESC")
    @date = Day.new
    @records = Record.all
    feeding_total_time = Record.where(activity: ["Feeding", "Scatter Feed"]).pluck(:total)
    if feeding_total_time.count >= 1
      @feeding_average = feeding_total_time.reduce(:+).fdiv(feeding_total_time.size).round(0)
    else
      @feeding_average = 0
    end

    @feeding_max = Record.where(activity: ["Feeding", "Scatter Feed"]).pluck(:total).max
    @feeding_min = Record.where(activity: ["Feeding", "Scatter Feed"]).pluck(:total).min
    zone_array = Record.pluck(:zone)
    hash_count = zone_array.inject(Hash.new(0)) { |h, e| h[e] += 1 ; h }
    empt_arr = []
    hash_count.each do |k,v|
      if v == hash_count.values.max
        empt_arr << k
      end
    end

    if empt_arr.count > 1
      @most_frequented_zone = empt_arr.join(",")
    else 
      @most_frequented_zone = empt_arr[0]
    end
    # @most_frequented_zone = zone_array.max_by { |i| zone_array.count(i) }

    respond_to do |format|
      format.html
      format.csv { send_data @dates.to_csv}
      format.xls { send_data @dates.to_csv(col_sep: "\t")}
    end

  end

  def create
    @date = Day.new(date_params)
    if @date.save
      redirect_to date_path(id: @date.id)
    else
      render :index
    end
  end

  def edit
    @date = Day.find(params[:id])
  end

  def update
    @date = Day.find(params[:id])
    if @date.update(date_params)
      redirect_to date_path(id: @date.id)
    else
      render :edit
    end
  end

  def destroy
    @date = Day.find(params[:id])
    @date.destroy
    redirect_to dates_path
  end

  def show
    @date = Day.find(params[:id])
    @record = @date.records.new
    @records = Day.find(params[:id]).records
  end

  private

  def date_params
    params.require(:day).permit(:date)
  end

end

app/helpers/dates_helper.rb
module DatesHelper
end

app/views/dates/edit.html.erb
<div class="container-fluid">
<br>
  <div class="form-inline my-2 my-lg-0">
  <%= form_for @date, url: date_path(id: @date.id), method: :put do |f| %>
    <%= f.number_field :date, class: "form-control mr-sm-2" %>
    <%= f.submit "update", class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
    <%= link_to "X", date_path(id: @date.id), class: "btn btn-outline-danger" %>
  </div>
</div>

app/views/dates/index.html.erb
<div class="container-fluid">

<!-- //////////////////////// overall data dashboard for without feedpod /////////////////////////  -->

  <div class="row dashboard">
    <div class="container-fluid">
      <br>
      <span class="showdate">OVERALL DATA</span><br>
      Total days: <span class="dashdata"><%= @dates.count %></span>&nbsp;&nbsp;&nbsp;
      Total Records: <span class="dashdata"><%= @records.count %></span>&nbsp;&nbsp;&nbsp;
      Feeding average per zone: <span class="dashdata"><%= @feeding_average %> mins</span><br>
      Longest feeding time: <span class="dashdata"><%= @feeding_max %> mins</span>&nbsp;&nbsp;&nbsp;
      Shortest feeding time: <span class="dashdata"><%= @feeding_min %> mins</span>&nbsp;&nbsp;&nbsp;
      Most Frequented Zone: <span class="dashdata"><%= @most_frequented_zone %></span>

      <br><br>

      <div class="row">
        <div class="col"></div>
        <div class="col">
          <%= form_for @date, url: dates_path, method: :post do |form| %>
            <%= form.number_field :date, class: "form-control mr-sm-2 input", placeholder: "DDMMYY" %><br>
            <%= form.submit "New Date", class: "btn btn-outline-warning my-2 my-sm-0" %>
          <% end %>
        </div>
        <div class="col"></div>
      </div>
      
    
    </div>
  </div>

  <div class="row">
    <div class="col"></div>
      <div class="showdate col">Dates <span class="withwithout">WITHOUT</span> Feedpod</div>
    <div class="col"></div>
  </div>
  

<!-- //////////////////////// all dates records index /////////////////////////  -->
  
  <div>
    <% @dates.each do |day| %>
      DATE: <%= link_to day.date, date_path(id: day.id), class: "link" %>
      <%= link_to "<i class=\"fa fa-trash-alt trash\"></i> ".html_safe, date_path(id: day.id), method: :delete, data: {confirm: "Delete: Are you sure?"} %>

      <br><br>
      
      <% arr = [] %>
      <% arr2 = []%>
      <% arr3 = [] %>


      <table class="table table-striped table-dark">
        <thead class="thead">
          <tr>
            <th scope="col">TIME START</th>
            <th scope="col">TIME END</th>
            <th scope="col">TIME TOTAL</th>
            <th scope="col">ZONE</th>
            <th scope="col">TIME ACTIVITY</th>
          </tr>
        </thead>
        <% day.records.each do |record| %>
        <tbody>
          <tr>
            <td><%= record.time_start %></td>
            <td><%= record.time_end %></td>
            <td><%= record.total %> mins</td>
            <td><%= record.zone %></td>
            <td><%= record.activity %></td>
          </tr>
        </tbody>
        <% if record.activity == "Feeding" || record.activity == "Scatter Feed" %>
          <% arr << record.total %>
        <% end %>

        <% end %>
      </table>
      
      
      <div class="dashboard-date">
        &nbsp;&nbsp;&nbsp;
        Total Feeding time: <span class="dashdata"><%= arr.inject(:+) %> mins</span>&nbsp;&nbsp;&nbsp;
        Longest Feeding Time: <span class="dashdata"><%= arr.max %> mins</span>&nbsp;&nbsp;&nbsp;
        Shortest Feeding Time: <span class="dashdata"><%= arr.min %> mins</span>&nbsp;&nbsp;&nbsp;
      </div>
         
      <br>
      
      <hr>

    <% end %>  
  </div>
</div>

app/views/dates/show.html.erb
<div class="container-fluid">
  <span class="showdate">W/O Feedpod Date: <%= @date.date %></span>
  <%= link_to " <i class=\"fas fa-wrench editshow\"></i> ".html_safe, edit_date_path(@date) %>

  <br><br>

<!-- ////////////////////////////// form ///////////////////////////-->

  <div class="row">
    <div class="col">
      <%= form_for @record, url: date_records_path(date_id: @date.id), method: :post do |f| %>
      <%= f.label :time_start %>
      <%= f.number_field :time_start, class: "form-control", placeholder: "eg. 1930" %>
    </div>

    <div class="col">
      <%= f.label :time_end %>
      <%= f.number_field :time_end, class: "form-control", placeholder: "eg. 2045" %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="container-fluid">
      <%= f.label :Location %>
      <%= f.select :zone, [
        ['Hay Feeder Box Front', 'Hay Feeder Box Front'], 
        ['Grass Feeder Box', 'Grass Feeder Box'], 
        ['Hay Feeder Box Pool', 'Hay Feeder Box Pool'], 
        ['Feedpod', 'Feedpod'],
        ['Front of exhibit', 'Front of exhibit'],
        ['Exhibit Left Facing', 'Exhibit Left Facing'], 
        ['Exhibit Right Facing', 'Exhibit Right Facing'], 
        ['Exhibit BOH Facing', 'Exhibit BOH Facing']], 
        {}, {class: "form form-group form-control", size: "8"} %>
    </div>
  </div>

  <div class="row">
    <div class="container-fluid">
      <%= f.label :Activity %>
      <%= f.select :activity, [
        ['Feeding', 'Feeding'],
        ['Scatter Feed', 'Scatter Feed'],
        ['Other', 'Other']],
        {}, {class: "form form-group form-control", size: "3"} %>
    </div>
  </div>

  <div class="row">
    <div class="container-fluid">
      <%= f.submit "Add Record", class: "btn btn-warning btn-lg btn-block" %>
    </div>
  </div>

  <% end %>

  <hr>

  <!-- //////////////////////// records for the day /////////////////////////  -->

  <table class="table table-striped table-dark">
    <thead class="thead">
      <tr>
        <th scope="col">TIME START</th>
        <th scope="col">TIME END</th>
        <th scope="col">TIME TOTAL</th>
        <th scope="col">ZONE</th>
        <th scope="col">TIME ACTIVITY</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <% @records.each do |record| %>
    <tbody>
      <tr>
        <td><%= record.time_start %></td>
        <td><%= record.time_end %></td>
        <td><%= record.total %> mins</td>
        <td><%= record.zone %></td>
        <td><%= record.activity %></td>
        <td><%= link_to "<i class=\"fa fa-trash-alt trash\"></i> ".html_safe, date_record_path(date_id: @date.id, id: record.id), method: :delete %></td>
      </tr>
    </tbody>
    <% end %>
  </table>

</div>