config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  resources :dates, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :records, only: [:create, :destroy]
  end

  resources :feedpod_dates, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :feedpod_records, only: [:create, :destroy]
  end

  resources :insights, only: [:index]

  get 'statics/visual'
  get 'statics/exhibit'

  root 'insights#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feedpod_date.rb
class FeedpodDate < ApplicationRecord
  has_many :feedpodrecords, dependent: :destroy
  validates :date, presence: true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << record_column_names = %w{id date created_at updated_at zone time_start time_end total activity}

      all.each do |date|
        date.feedpodrecords.each do |record|
          csv << date.attributes.values_at(*column_names)
          csv << record.attributes.values_at(*record_column_names)
        end
      end
    end
  end
end

app/controllers/feedpod_dates_controller.rb
class FeedpodDatesController < ApplicationController

  def index
    @dates = FeedpodDate.all.order("created_at DESC")
    @date = FeedpodDate.new
    @feedpodrecords = Feedpodrecord.all
    feeding_total_time = Feedpodrecord.where(activity: ["Feeding", "Scatter Feed"]).pluck(:total)
    if feeding_total_time.count >= 1
      @feeding_average = feeding_total_time.reduce(:+).fdiv(feeding_total_time.size).round(0)
    else
      @feeding_average = 0
    end

    @feeding_max = Feedpodrecord.where(activity: ["Feeding", "Scatter Feed"]).pluck(:total).max
    @feeding_min = Feedpodrecord.where(activity: ["Feeding", "Scatter Feed"]).pluck(:total).min
    zone_array = Feedpodrecord.pluck(:zone)
    hash_count = zone_array.inject(Hash.new(0)) { |h, e| h[e] += 1 ; h }
    empt_arr = []
    hash_count.each do |k,v|
      if v == hash_count.values.max
        empt_arr << k
      end
    end

    if empt_arr.count > 1
      @most_frequented_zone = empt_arr.join(", ")
    else 
      @most_frequented_zone = empt_arr[0]
    end
    # @most_frequented_zone = zone_array.max_by { |i| zone_array.count(i) }

    respond_to do |format|
      format.html
      format.csv { send_data @dates.to_csv}
      format.xls { send_data @dates.to_csv(col_sep: "\t")}
    end

  end

  def create
    @date = FeedpodDate.new(date_params)
    if @date.save
      redirect_to feedpod_date_path(id: @date.id)
    else
      render :index
    end
  end

  def edit
    @date = FeedpodDate.find(params[:id])
  end

  def update
    @date = FeedpodDate.find(params[:id])
    if @date.update(date_params)
      redirect_to feedpod_date_path(id: @date.id)
    else
      render :edit
    end
  end

  def destroy
    @date = FeedpodDate.find(params[:id])
    @date.destroy
    redirect_to feedpod_dates_path
  end

  def show
    @date = FeedpodDate.find(params[:id])
    @feedpodrecord = @date.feedpodrecords.new
    @feedpodrecords = FeedpodDate.find(params[:id]).feedpodrecords
  end

  private

  def date_params
    params.require(:feedpod_date).permit(:date)
  end

end

app/helpers/feedpod_dates_helper.rb
module FeedpodDatesHelper
end

app/views/feedpod_dates/edit.html.erb
<div class="container-fluid">
<br>
  <div class="form-inline my-2 my-lg-0">
  <%= form_for @date, url: feedpod_date_path(id: @date.id), method: :put do |f| %>
    <%= f.number_field :date, class: "form-control mr-sm-2" %>
    <%= f.submit "update", class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
    <%= link_to "X", feedpod_date_path(id: @date.id), class: "btn btn-outline-danger" %>
  </div>
</div>

app/views/feedpod_dates/index.html.erb
<div class="container-fluid">

<!-- //////////////////////// overall data dashboard for with feedpod /////////////////////////  -->

  <div class="row dashboardfeedpod">
    <div class="container-fluid">
      <br>
      <span class="showdate">OVERALL DATA</span><br>
      Total days: <span class="dashdatafeed"><%= @dates.count %></span>&nbsp;&nbsp;&nbsp;
      Total Records: <span class="dashdatafeed"><%= @feedpodrecords.count %></span>&nbsp;&nbsp;&nbsp;
      Feeding average per zone: <span class="dashdatafeed"><%= @feeding_average %> mins</span><br>
      Longest feeding time: <span class="dashdatafeed"><%= @feeding_max %> mins</span>&nbsp;&nbsp;&nbsp;
      Shortest feeding time: <span class="dashdatafeed"><%= @feeding_min %> mins</span>&nbsp;&nbsp;&nbsp;
      Most Frequented Zone: <span class="dashdatafeed"><%= @most_frequented_zone %></span>

      <br><br>

      <div class="row">
        <div class="col"></div>
        <div class="col">
          <%= form_for @date, url: feedpod_dates_path, method: :post do |form| %>
            <%= form.number_field :date, class: "form-control mr-sm-2 input", placeholder: "DDMMYY" %><br>
            <%= form.submit "New Date", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        </div>
        <div class="col"></div>
      </div>
      
    
    </div>
  </div>

  <div class="row">
    <div class="col"></div>
      <div class="showdate col">Dates <span class="withwithout">WITH</span> Feedpod</div>
    <div class="col"></div>
  </div>
  

<!-- //////////////////////// all dates records index /////////////////////////  -->
  
  <div>
    <% @dates.each do |day| %>
      DATE: <%= link_to day.date, feedpod_date_path(id: day.id), class: "link" %>
      <%= link_to "<i class=\"fa fa-trash-alt trash\"></i> ".html_safe, feedpod_date_path(id: day.id), method: :delete, data: {confirm: "Delete: Are you sure?"} %>

      <br><br>
      
      <% arr = [] %>
      <% arr2 = []%>
      <% arr3 = [] %>

      <table class="table table-striped table-dark">
        <thead class="thead">
          <tr>
            <th scope="col">TIME START</th>
            <th scope="col">TIME END</th>
            <th scope="col">TIME TOTAL</th>
            <th scope="col">ZONE</th>
            <th scope="col">TIME ACTIVITY</th>
          </tr>
        </thead>
        <% day.feedpodrecords.each do |record| %>
        <tbody>
          <tr>
            <td><%= record.time_start %></td>
            <td><%= record.time_end %></td>
            <td><%= record.total %> mins</td>
            <td><%= record.zone %></td>
            <td><%= record.activity %></td>
          </tr>
        </tbody>
        <% if record.activity == "Feeding" || record.activity == "Scatter Feed" %>
          <% arr << record.total %>
        <% end %>

        <% end %>
      </table>
      
      
      <div class="dashboard-date-feed">
        &nbsp;&nbsp;&nbsp;
        Total Feeding time: <span class="dashdatafeed"><%= arr.inject(:+) %> mins</span>&nbsp;&nbsp;&nbsp;
        Longest Feeding Time: <span class="dashdatafeed"><%= arr.max %> mins</span>&nbsp;&nbsp;&nbsp;
        Shortest Feeding Time: <span class="dashdatafeed"><%= arr.min %> mins</span>&nbsp;&nbsp;&nbsp;
      </div>
         
      <br>
      
      <hr>

    <% end %>  
  </div>
</div>

app/views/feedpod_dates/show.html.erb
<div class="container-fluid">
  <span class="showdate">WITH Feedpod Date: <%= @date.date %></span>
  <%= link_to " <i class=\"fas fa-wrench editshow\"></i> ".html_safe, edit_feedpod_date_path(@date) %>

  <br><br>

<!-- ////////////////////////////// form ///////////////////////////-->

  <div class="row">
    <div class="col">
      <%= form_for @feedpodrecord, url: feedpod_date_feedpod_records_path(feedpod_date_id: @date.id), method: :post do |f| %>
      <%= f.label :time_start %>
      <%= f.number_field :time_start, class: "form-control", placeholder: "eg. 1930" %>
    </div>

    <div class="col">
      <%= f.label :time_end %>
      <%= f.number_field :time_end, class: "form-control", placeholder: "eg. 2045" %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="container-fluid">
      <%= f.label :Location %>
      <%= f.select :zone, [
        ['Hay Feeder Box Front', 'Hay Feeder Box Front'], 
        ['Grass Feeder Box', 'Grass Feeder Box'], 
        ['Hay Feeder Box Pool', 'Hay Feeder Box Pool'], 
        ['Feedpod', 'Feedpod'],
        ['Front of exhibit', 'Front of exhibit'],
        ['Exhibit Left Facing', 'Exhibit Left Facing'], 
        ['Exhibit Right Facing', 'Exhibit Right Facing'], 
        ['Exhibit BOH Facing', 'Exhibit BOH Facing']], 
        {}, {class: "form form-group form-control", size: "8"} %>
    </div>
  </div>

  <div class="row">
    <div class="container-fluid">
      <%= f.label :Activity %>
      <%= f.select :activity, [
        ['Feeding', 'Feeding'],
        ['Scatter Feed', 'Scatter Feed'],
        ['Other', 'Other']],
        {}, {class: "form form-group form-control", size: "3"} %>
    </div>
  </div>

  <div class="row">
    <div class="container-fluid">
      <%= f.submit "Add Record", class: "btn btn-success btn-lg btn-block" %>
    </div>
  </div>

  <% end %>

  <hr>

  <!-- //////////////////////// records for the day /////////////////////////  -->

  <table class="table table-striped table-dark">
    <thead class="thead">
      <tr>
        <th scope="col">TIME START</th>
        <th scope="col">TIME END</th>
        <th scope="col">TIME TOTAL</th>
        <th scope="col">ZONE</th>
        <th scope="col">TIME ACTIVITY</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <% @feedpodrecords.each do |record| %>
    <tbody>
      <tr>
        <td><%= record.time_start %></td>
        <td><%= record.time_end %></td>
        <td><%= record.total %> mins</td>
        <td><%= record.zone %></td>
        <td><%= record.activity %></td>
        <td><%= link_to "<i class=\"fa fa-trash-alt trash\"></i> ".html_safe, feedpod_date_feedpod_record_path(feedpod_date_id: @date.id, id: record.id), method: :delete %></td>
      </tr>
    </tbody>
    <% end %>
  </table>

</div>