config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  resources :dates, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :records, only: [:create, :destroy]
  end

  resources :feedpod_dates, only: [:index, :create, :destroy, :show, :edit, :update] do
    resources :feedpod_records, only: [:create, :destroy]
  end

  resources :insights, only: [:index]

  get 'statics/visual'
  get 'statics/exhibit'

  root 'insights#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dataapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Finger+Paint" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  </head>

  <body class="<%= @visual ? 'visual' : '' %>">
    <% flash.class %>
      <%-flash.each do |key,value| %>
        <% key %>
        <div class="notice"><%= value %></div>
      <% end %>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand home animated pulse" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">CWANG</a>

      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "Full Data Insight", root_path, class: "dropdown-item" %>
        <%= link_to "Data Visualisation", statics_visual_path, class: "dropdown-item" %>
        <%= link_to "Exhibit Layout", statics_exhibit_path, class: "dropdown-item" %>
        <!-- <div class="dropdown-divider"></div> -->
      </div>

      <% if current_page?(dates_path) %>
        <%= link_to "Go To Feedpod Index", feedpod_dates_path, class: "btn btn-success" %> <span id="space">|</span>
        <%= link_to "Export as CSV", dates_path(format: "csv"), class: "btn btn-info" %>
      <% elsif current_page?(feedpod_dates_path) %>
        <%= link_to "Go To W/O Feedpod Index", dates_path, class: "btn btn-warning" %> <span id="space">|</span>
        <%= link_to "Export as CSV", feedpod_dates_path(format: "csv"), class: "btn btn-light" %>
      <% else %>
        <%= link_to "Go To Feedpod Index", feedpod_dates_path, class: "btn btn-success" %> <span id="space">|</span>
        <%= link_to "Go To W/O Feedpod Index", dates_path, class: "btn btn-warning" %>
        
      <% end %>
    </nav>
    
    <%= yield %>
  </body>
</html>